### ISSUE TITLE
Prefixes helpers with `this.`

### ISSUE THREAD

**Issue by kategengler** [ember-codemods/ember-no-implicit-this-codemod#33]
```{{not foo}}``` becomes ```{{this.not this.foo}}```

**Comment by NullVoxPopuli** [comment]
Hmm. I think there is a discrepancy between mock telemetry, and telemetry collected from the running ember app :(

what ember version are you using, @kategengler there is a problem with ember 3.13+, that is addressed by https://github.com/ember-codemods/ember-no-implicit-this-codemod/pull/29
which is blocked by https://github.com/ember-codemods/ember-codemods-telemetry-helpers/pull/20

**Comment by kategengler** [comment]
Ember 3.13.3

#29 Looks like test-only chances, how does it fix ember 3.13+?

**Comment by NullVoxPopuli** [comment]
The telemetry changes are more what fixes it. #29 just ensures that both old a new ember still 'work' with this codemod.

There was a change in how object meta is collected / built in 3.13, so that's why this codemod in broken in recent 3.13+.

Once the telemetry PR is merged, I'll get a release out for this codemod asap ;)

**Comment by NullVoxPopuli** [comment]
I've been able to replicate this with #39 with ember-truth-helpers installed. :tada: Fix incoming

**Comment by Turbo87** [comment]
I can confirm that both truth-helpers, but also (some) custom app helpers are getting prefixed with `this.`.

**Comment by NullVoxPopuli** [comment]
Resolved in #39 and released in 0.7.3. Thanks for reporting! <3
