### ISSUE TITLE
Support a config option to augment the telemetry data

### ISSUE THREAD

**Issue by suchitadoshi1987** [ember-codemods/ember-no-implicit-this-codemod#47]
We have a case where one of the helpers is driven by AST transform (build-time-helper) and hence it's not detected when the codemod is run. With a config option, it would open doors for handling such weird/custom usecases.

**Comment by NullVoxPopuli** [comment]
What sort of config option would be most ergonomic for you?

**Comment by rwjblue** [comment]
I think this would probably need to be an additional flag to be passed to the command line invocation. E.g.

```
npx ember-no-implicit-this-codemod http://localhost:4200 app/**/*.hbs --additional-helpers=comma,separated,list,here
```

**Comment by NullVoxPopuli** [comment]
I think my preference is `--additional-helpers` :+1:

**Comment by hmajoros** [comment]
One man's opinion, but since it's likely that folks will be running this codemod + the angle-brackets codemod in tandem, it might make sense to align on how additional helpers are passed in. 

I'd recommend allowing a `--config` flag, like [ember-angle-brackets-codemod](https://github.com/ember-codemods/ember-angle-brackets-codemod) does:

```
$ npx ember-angle-brackets-codemod angle-brackets app/templates --config ./config/anglebrackets-codemod-config.json
```

with the config looking like this:
```
{
  "helpers": [
    "date-formatter", 
    "info-pill"
  ]
}
```

**Comment by rwjblue** [comment]
Ya, makes sense to me
